plugins:
  email_extension_enabled:
    default: false
    client: true
  email_extension_reply_by_email_address:
    default: "reply+p%{post_id}@example.com"
    client: true
    type: list
  email_extension_topic_reply_subject_headers:
    default: "Re:|RE:|re:|回复:|回复："
    client: true
    type: list
  edit_email_subject:
    default: "[%{site_name}] [edit to #%{edit_post_id}]%{topic_title}"
    client: false

